-- Update passwords with the correct BCrypt hash for 'admin123'
-- This hash was generated by BCrypt and verified to work

UPDATE users SET password = '$2a$10$ji9dJdApPT0dgOl5ohFxc.lu3cAs1T7tw6s.Lzi7FzdMu70sE8FLG' WHERE email = 'admin@reliablecarriers.com';
UPDATE users SET password = '$2a$10$ji9dJdApPT0dgOl5ohFxc.lu3cAs1T7tw6s.Lzi7FzdMu70sE8FLG' WHERE email = 'driver@reliablecarriers.com';
UPDATE users SET password = '$2a$10$ji9dJdApPT0dgOl5ohFxc.lu3cAs1T7tw6s.Lzi7FzdMu70sE8FLG' WHERE email = 'sarah.wilson@reliablecarriers.com';
UPDATE users SET password = '$2a$10$ji9dJdApPT0dgOl5ohFxc.lu3cAs1T7tw6s.Lzi7FzdMu70sE8FLG' WHERE email = 'michael.brown@reliablecarriers.com';
UPDATE users SET password = '$2a$10$ji9dJdApPT0dgOl5ohFxc.lu3cAs1T7tw6s.Lzi7FzdMu70sE8FLG' WHERE email = 'lisa.garcia@reliablecarriers.com';
UPDATE users SET password = '$2a$10$ji9dJdApPT0dgOl5ohFxc.lu3cAs1T7tw6s.Lzi7FzdMu70sE8FLG' WHERE email = 'david.martinez@reliablecarriers.com';
UPDATE users SET password = '$2a$10$ji9dJdApPT0dgOl5ohFxc.lu3cAs1T7tw6s.Lzi7FzdMu70sE8FLG' WHERE email = 'emma.johnson@reliablecarriers.com';
UPDATE users SET password = '$2a$10$ji9dJdApPT0dgOl5ohFxc.lu3cAs1T7tw6s.Lzi7FzdMu70sE8FLG' WHERE email = 'customer@example.com';

-- Verify the updates
SELECT email, password FROM users;
